version: "2"

services: 
  api:
    build: .
    command: npm run dev
    environment:
      - DEBUG=server:*,server-redis:*,worker:*,converter-ffmpeg:*,converter-redis:*
      - DEBUG_COLORS=true
      - WORKER_STARTUP_SECONDS=1
    ports:
      - "8080:8080"
    links:
      - redis
      - rabbitmq
    volumes: 
      - api-deps:/code/node_modules
      - .:/code

  redis:
    image: "redis:alpine"

  rabbitmq:
    image: "rabbitmq:latest"
    # environment:
    #  - RABBITMQ_HIPE_COMPILE=1

volumes:
  api-deps: